apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8app-backend
  namespace: backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: k8app-backend

  template:
    metadata:
      labels:
        app: k8app-backend

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 80
