apiVersion: v1
kind: Secret
metadata:
  name: k8app-backend-secret
  namespace: backend
type: Opaque

stringData:
  POSTGRES_USER: {{ .Values.backend.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.backend.secret.postgresPassword | quote }}
